# Generated by Django 4.2 on 2023-05-06 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamiento',
            fields=[
                ('hora', models.IntegerField(db_comment='guarda la hora de la cita \n', primary_key=True, serialize=False)),
                ('lugar', models.CharField(blank=True, db_comment='guarda la ubicacion de la cita ', max_length=45, null=True)),
                ('nombre', models.CharField(blank=True, db_comment='guarda el nombre de quien cita ', max_length=45, null=True)),
            ],
            options={
                'db_table': 'agendamiento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cateserv',
            fields=[
                ('idcateserv', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'cateserv',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ctaller',
            fields=[
                ('ctaller', models.IntegerField(db_comment='guarda el registro de cada taller ', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_comment='guarda el servicio que a prestar ', max_length=45, null=True)),
                ('nombre', models.CharField(blank=True, db_comment='guarda el nombre de cada taller ', max_length=45, null=True)),
            ],
            options={
                'db_table': 'ctaller',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('idempresa', models.IntegerField(db_comment='guarda el numero de registro de la empresa', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_comment='guarda el nombre de la empresa ', max_length=45, null=True)),
                ('direccion', models.CharField(blank=True, db_comment='guarda la direccion de la empresa ', max_length=45, null=True)),
                ('telefono', models.CharField(blank=True, db_comment='guarda el contacto de la empresa ', max_length=45, null=True)),
                ('correo', models.CharField(blank=True, db_comment='guarda el correo de la empresa ', max_length=45, null=True)),
                ('razonsocial', models.CharField(blank=True, db_comment='guarda el nombre juridico de la empresa', max_length=45, null=True)),
                ('catgtall', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='principal.ctaller')),
            ],
            options={
                'db_table': 'empresa',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Factcabeza',
            fields=[
                ('idfactura', models.IntegerField(db_comment='guarda registro de factura ', primary_key=True, serialize=False)),
                ('cliente', models.CharField(blank=True, max_length=45, null=True)),
                ('fecha', models.CharField(blank=True, max_length=45, null=True)),
                ('valor_unitario', models.CharField(blank=True, db_column='valor unitario', max_length=45, null=True)),
                ('valortotal', models.CharField(blank=True, max_length=45, null=True)),
                ('pagos_tarjetacredito', models.IntegerField()),
            ],
            options={
                'db_table': 'factcabeza',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('idmunicipio', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('ciudad_idciudad', models.IntegerField()),
            ],
            options={
                'db_table': 'municipio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Scripcion',
            fields=[
                ('idscripcion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('valor', models.CharField(blank=True, max_length=45, null=True)),
                ('fecha', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'scripcion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tdoc',
            fields=[
                ('idtdoc', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'tdoc',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tipersona',
            fields=[
                ('idtipersona', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'tipersona',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('idservicio', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('cateserv_idcateserv', models.ForeignKey(db_column='cateserv_idcateserv', on_delete=django.db.models.deletion.DO_NOTHING, to='principal.cateserv')),
            ],
            options={
                'db_table': 'servicio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Planes',
            fields=[
                ('idplanes', models.IntegerField(db_comment='guarda registro de cada plan \n', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_comment='guarda las promociones de cada taller \n', max_length=45, null=True)),
                ('nombre', models.CharField(blank=True, db_comment='guarda el nombre del plan ', max_length=45, null=True)),
                ('servicio_idservicio', models.ForeignKey(db_column='servicio_idservicio', on_delete=django.db.models.deletion.DO_NOTHING, to='principal.servicio')),
            ],
            options={
                'db_table': 'planes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pgos',
            fields=[
                ('idpgos', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
                ('factcabeza_idfactura', models.ForeignKey(db_column='factcabeza_idfactura', on_delete=django.db.models.deletion.DO_NOTHING, to='principal.factcabeza')),
            ],
            options={
                'db_table': 'pgos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('idpersona', models.AutoField(db_comment='guarda  identificando individualmente el registro de cada persona.\n', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_comment='guarda el nombre del usuario ', max_length=45)),
                ('apellido', models.CharField(db_comment='guarda el apellido del usuario', max_length=45)),
                ('telefono', models.CharField(db_comment='guardara el contacto del usuario ', max_length=45)),
                ('correo', models.CharField(db_comment='guardara el correo del usuario', max_length=45)),
                ('contrasena', models.CharField(db_comment='guarda la contrase�a del usuario', max_length=45)),
                ('genero', models.CharField(blank=True, max_length=45, null=True)),
                ('fechanacimiento', models.DateField(blank=True, null=True)),
                ('tipersona_idtipersona', models.IntegerField()),
                ('municipio_idmunicipio', models.ForeignKey(db_column='municipio_idmunicipio', on_delete=django.db.models.deletion.DO_NOTHING, to='principal.municipio')),
                ('tdoc_idtdoc', models.ForeignKey(db_column='tdoc_idtdoc', on_delete=django.db.models.deletion.DO_NOTHING, to='principal.tdoc')),
                ('tipersona_idtipersona1', models.ForeignKey(db_column='tipersona_idtipersona1', on_delete=django.db.models.deletion.DO_NOTHING, to='principal.tipersona')),
            ],
            options={
                'db_table': 'persona',
                'managed': True,
                'unique_together': {('idpersona', 'tipersona_idtipersona', 'tipersona_idtipersona1')},
            },
        ),
        migrations.CreateModel(
            name='Listadoempresaservicio',
            fields=[
                ('idlistadoempresaservicio', models.IntegerField(primary_key=True, serialize=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='principal.empresa')),
                ('servicio_idservicio', models.ForeignKey(db_column='servicio_idservicio', on_delete=django.db.models.deletion.DO_NOTHING, to='principal.servicio')),
            ],
            options={
                'db_table': 'listadoempresaservicio',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='factcabeza',
            name='persona_idpersona',
            field=models.ForeignKey(db_column='persona_idpersona', on_delete=django.db.models.deletion.DO_NOTHING, to='principal.persona'),
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('iddepartamento', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('codigo', models.CharField(blank=True, max_length=45, null=True)),
                ('municipio_idmunicipio', models.ForeignKey(db_column='municipio_idmunicipio', on_delete=django.db.models.deletion.DO_NOTHING, to='principal.municipio')),
            ],
            options={
                'db_table': 'departamento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cuerpo',
            fields=[
                ('idcuerpo', models.IntegerField(primary_key=True, serialize=False)),
                ('idcabeza', models.CharField(blank=True, max_length=45, null=True)),
                ('cantidad', models.CharField(blank=True, max_length=45, null=True)),
                ('valorunitariol', models.CharField(blank=True, max_length=45, null=True)),
                ('valortotal', models.CharField(blank=True, max_length=45, null=True)),
                ('factcabeza_idfactura', models.ForeignKey(db_column='factcabeza_idfactura', on_delete=django.db.models.deletion.DO_NOTHING, to='principal.factcabeza')),
                ('scripcion_idscripcion', models.ForeignKey(db_column='scripcion_idscripcion', on_delete=django.db.models.deletion.DO_NOTHING, to='principal.scripcion')),
            ],
            options={
                'db_table': 'cuerpo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('idcontrato', models.IntegerField(db_comment='guarda registro de contrato que realiza la empresa ', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_comment='guarda los terminos y condiciones de cada contrato ', max_length=45, null=True)),
                ('nombre', models.CharField(blank=True, db_comment='guarda el nombre del contrato ', max_length=45, null=True)),
                ('persona_idpersona', models.ForeignKey(db_column='persona_idpersona', on_delete=django.db.models.deletion.DO_NOTHING, to='principal.persona')),
                ('servicio_idservicio', models.ForeignKey(db_column='servicio_idservicio', on_delete=django.db.models.deletion.DO_NOTHING, to='principal.servicio')),
            ],
            options={
                'db_table': 'contrato',
                'managed': True,
            },
        ),
    ]
