# Generated by Django 4.2 on 2023-04-25 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agendamiento',
        ),
        migrations.DeleteModel(
            name='Cateserv',
        ),
        migrations.DeleteModel(
            name='Contrato',
        ),
        migrations.DeleteModel(
            name='Ctaller',
        ),
        migrations.DeleteModel(
            name='Cuerpo',
        ),
        migrations.DeleteModel(
            name='Departamento',
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
        migrations.DeleteModel(
            name='Factcabeza',
        ),
        migrations.DeleteModel(
            name='Listadoempresaservicio',
        ),
        migrations.DeleteModel(
            name='Municipio',
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
        migrations.DeleteModel(
            name='Pgos',
        ),
        migrations.DeleteModel(
            name='Planes',
        ),
        migrations.DeleteModel(
            name='Scripcion',
        ),
        migrations.DeleteModel(
            name='Servicio',
        ),
        migrations.DeleteModel(
            name='Tdoc',
        ),
        migrations.DeleteModel(
            name='Tipersona',
        ),
    ]
